### ISSUE TITLE
Could not use images from sitecore\docker-images

### ISSUE THREAD

**Issue by Antonytm** [Sitecore/Sitecore.Demo.Platform#177]
Steps to reproduce:

1. Build docker images from sitecore\docker-images repository
2. Run docker-compose up -d

Expected result: docker images ready for deployment of demo site should be up and running
Actual result: Error

> Step 3/3 : COPY data/App_data/jobs/continuous/IndexWorker/ /worker
> ERROR: Service 'xconnect-indexworker' failed to build: COPY failed: CreateFile \\?\E:\ProgramData\Docker\tmp\docker-builder053997248\data\App_data\jobs\continuous\IndexWorker: The system cannot find the path specified.
> PS E:\Source\Sitecore.HabitatHome.Platform> docker-compose up -d

3. Attempt to ignore error by editing Sitecore.HabitatHome.Platform\docker\images\windows\demo-xp-xconnect-indexworker\dockerfile and removing line

`COPY data/App_data/jobs/continuous/IndexWorker/ /worker`

Expected result: docker images ready for deployment of demo site should be up and running
Actual result: Error

> Step 4/4 : RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\transforms\\web.config.xdt' -Recurse ) | ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\web.config' -XdtPath $_.FullName -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };
>  ---> Running in 5592160a0417
> Get-ChildItem : Cannot find path 'C:\inetpub\wwwroot\transforms\' because it
> does not exist.
> At line:1 char:77
> \+ ... Continue'; (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\transforms\\we ...
> \+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\inetpub\wwwroot\transforms\:
>    String) [Get-ChildItem], ItemNotFoundException
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCh
>    ildItemCommand

![image](https://user-images.githubusercontent.com/647813/72958703-a16c7700-3db0-11ea-9722-acb4c6582111.png)

**It looks like images in sitecore\docker-images repository, and images expected in this demo are different images.**

**Comment by phaniav** [comment]
@Antonytm I got same error as above. And I commented the step #4 in the file below. 
```\Sitecore.HabitatHome.Platform\docker\images\windows\demo-xp-standalone\Dockerfile```
This allowed me to spin up new Docker containers and also deploy the habitat home into it.

**Comment by wavveen** [comment]
The actual problem is that the following items are missing in the git repository:
- The "docker\images\windows\demo-xp-xconnect-indexworker\data\App_data\jobs\continuous\IndexWorker" folder. I'm not sure what should be in this folder
- The "docker\images\windows\demo-xp-standalone\Data\transforms\web.config.xdt" file. Not sure what should be in there as well.

"docker-compose up" works after creating a dummy folder and file for above items

@bplasmeijer Can you have a look at this?

**Comment by jeanfrancoislarente** [comment]
The empty placeholder folder is missing from the repo. That is indeed all that is required is an empty folder for the volume.

**Comment by wavveen** [comment]
@jeanfrancoislarente And what about the web.config.xdt?

**Comment by jeanfrancoislarente** [comment]
When you haven't yet built the habitat home images, the steps would be

1. Build base images from docker-images repo
1. run `.\build.ps1 -DeploymentTarget DockerBuild`
this will populate all of the docker\images context folders with demo build output
1. run `docker-compose build -m 16G --parallel`
 (16G and --parrallel are optional but provide additional resources to the build context)

Once the images are built then you can do a `docker-compose up`

**Comment by wavveen** [comment]
@jeanfrancoislarente I know how to build and run with docker. I'm just wondering what's supposed to be in that web.config.xdt which is missing...

**Comment by jeanfrancoislarente** [comment]
@wavveen 

My last comment to close the issue wasn't posted (I used another tool)

The `.\build.ps1 -DeploymentTarget DockerBuild` is what populates what you're looking for, including the web.config.xdt

Feel free to leave the sarcasm out of future help requests ;)

**Comment by wavveen** [comment]
@jeanfrancoislarente Then the "Local Build / Docker Deployment" instructions need to be rewritten, as step 1 is "Run docker-compose up -d" which will throw these exceptions:

`Step 3/3 : COPY data/App_data/jobs/continuous/IndexWorker/ /worker
ERROR: Service 'xconnect-indexworker' failed to build: COPY failed: CreateFile \?\E:\ProgramData\Docker\tmp\docker-builder053997248\data\App_data\jobs\continuous\IndexWorker: The system cannot find the path specified.
PS E:\Source\Sitecore.HabitatHome.Platform> docker-compose up -d`

`Step 4/4 : RUN (Get-ChildItem -Path 'C:\inetpub\wwwroot\transforms\web.config.xdt' -Recurse ) | ForEach-Object { & 'C:\tools\scripts\Invoke-XdtTransform.ps1' -Path 'C:\inetpub\wwwroot\web.config' -XdtPath $_.FullName -XdtDllPath 'C:\tools\bin\Microsoft.Web.XmlTransform.dll'; };
---> Running in 5592160a0417
Get-ChildItem : Cannot find path 'C:\inetpub\wwwroot\transforms' because it
does not exist.
At line:1 char:77
+ ... Continue'; (Get-ChildItem -Path 'C:\inetpub\wwwroot\transforms\we ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (C:\inetpub\wwwroot\transforms:
String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCh
ildItemCommand`

And then afterwards (in step 3) this command is executed: .\build.ps1 -DeploymentTarget DockerBuild

But without adding the "docker\images\windows\demo-xp-xconnect-indexworker\data\App_data\jobs\continuous\IndexWorker" folder and the "docker\images\windows\demo-xp-standalone\Data\transforms\web.config.xdt" file manually, you will never reach step 3 as you will be stuck in step 1 with the above mentioned exceptions.

**Comment by jeanfrancoislarente** [comment]
Speaking w/ @bplasmeijer  - he will try a clean build of this branch tomorrow and update the README as required.

We may have some items fixed internally that didn't make it out to GH yet.

**Comment by bplasmeijer** [comment]
@wavveen did you pull the latest docker-images from your local registry?

I did run the following test on a clean GitHub master branch check-out, 

1.) git clean -xdf 
2.) run .\build.ps1 -DeploymentTarget DockerBuild
the xconnect modules are copied;
![image](https://user-images.githubusercontent.com/116467/76065256-90a44900-5f8b-11ea-92c8-099333cca8c1.png)
3.) run docker-compose build -m 16G --no-cache

no build errors.
please ping me on slack @wavveen if the error continues. 

I will update the documentation in the next push.
Bart

**Comment by wavveen** [comment]
@bplasmeijer it's not during the "run .\build.ps1 -DeploymentTarget DockerBuild" that things go wrong. It's when running "docker-compose up -d" for the first time, when trying to create the demo images.

It has nothing to do with the docker-images from our local registry. 

As you can see, this folder is empty:
![2020-03-06 08_32_27-Sitecore HabitatHome Platform_docker_images_windows_demo-xp-standalone_Data at m](https://user-images.githubusercontent.com/6557188/76088135-84b58880-5f85-11ea-9f15-dda195a31768.png)

While this command in the dockerfile needs a "transforms/web.config.xdt" there
![2020-03-06 08_34_09-Sitecore HabitatHome Platform_Dockerfile at master · Sitecore_Sitecore HabitatHo](https://user-images.githubusercontent.com/6557188/76088325-cba37e00-5f85-11ea-96be-1f135bca5715.png)

**Comment by jeanfrancoislarente** [comment]
What is in the docker\images\windows\demo-xp-standalone\data folder _after_ your run `.\build.ps1 -DeploymentTarget DockerBuild`
?

**Comment by wavveen** [comment]
![2020-03-06 11_41_44-D__Projects_Sitecore HabitatHome Platform_docker_images_windows_demo-xp-standalo](https://user-images.githubusercontent.com/6557188/76103368-96a42500-5f9f-11ea-9726-84c7ffb3a985.png)

![2020-03-06 11_42_20-D__Projects_Sitecore HabitatHome Platform_docker_images_windows_demo-xp-standalo](https://user-images.githubusercontent.com/6557188/76103377-9ad04280-5f9f-11ea-95a4-95fe69c1dc4b.png)

**Comment by bplasmeijer** [comment]
I schedule a call @wavveen

**Comment by bplasmeijer** [comment]
> @wavveen did you pull the latest docker-images from your local registry?
> 
> I did run the following test on a clean GitHub master branch check-out,
> 
> 1.) git clean -xdf
> 2.) run .\build.ps1 -DeploymentTarget DockerBuild
> the xconnect modules are copied;
> ![image](https://user-images.githubusercontent.com/116467/76065256-90a44900-5f8b-11ea-92c8-099333cca8c1.png)
> 3.) run docker-compose build -m 16G --no-cache
> 4.) docker-compose up -d
> 
> no build errors.
> please ping me on slack @wavveen if the error continues.
> 
> I will update the documentation in the next push.
> Bart

@jeanfrancoislarente I will adjust the readme.md

run .\build.ps1 -DeploymentTarget DockerBuild # preperation for building the sitecore.habitathome.platform images
vs
> 2.) run .\build.ps1 -DeploymentTarget Docker # against running instance

**Comment by jeanfrancoislarente** [comment]
Correct, the instructions were not included for building images. Instead instructions assumed you were trying to deploy the assets against the images from the docker-images repo. However, the instructions provided in this thread were accurate.

**Comment by jeanfrancoislarente** [comment]
We've made some significant updates since this issue was opened @Antonytm - any chance this is now obsolete?

**Comment by Antonytm** [comment]
@jeanfrancoislarente yes, the issue could be closed.
