### ISSUE TITLE
Personalization not working: AssignPatternCardAction failed

### ISSUE THREAD

**Issue by dmead35** [Sitecore/Sitecore.Demo.Platform#194]
Steps:

1. https://cd.lighthouse.localhost/ In Chrome browser incognito mode
2. Articles
3. Automate Dinner
4. Scroll down --> Find Your Personalized Content
5. You're on https://cd.lighthouse.localhost/content-finder .  Click Child Safety
6. Click Next

Expected:
-Works, no error
-Tray on right (i icon) indicates that I am interested in Child Health

Actual:
-Refreshes https://cd.lighthouse.localhost/content-finder?sc_site=LighthouseLifestyle.  Says this (above the page headline): Failed to assign pattern cards!

Details from cd log:

2092 02:02:10 ERROR AssignPatternCardAction failed: Could not update pattern for card {C3E2C23C-5FE2-4FD1-97A1-14
Exception: System.Exception
Message: The profile definition does not exist - Health Focus
Source: Sitecore.Analytics
   at Sitecore.Analytics.Tracking.VisitProfiles.get_Item(String profileName)
   at Sitecore.Demo.Platform.Feature.Forms.SubmitActions.AssignPatternCardAction.Execute(AssignPatternActionData

2648 02:02:19 ERROR AssignPatternCardAction failed: Could not update pattern for card {C3E2C23C-5FE2-4FD1-97A1-14
Exception: System.Exception
Message: The profile definition does not exist - Health Focus
Source: Sitecore.Analytics
   at Sitecore.Analytics.Tracking.VisitProfiles.get_Item(String profileName)
   at Sitecore.Demo.Platform.Feature.Forms.SubmitActions.AssignPatternCardAction.Execute(AssignPatternActionData

**Comment by scottmulligan** [comment]
Due to the installation of items via Dacpacs into Sitecore containers, not all "Add Item" events are triggered in Sitecore as other approaches.

As part of the deployment to containers there is a special container run (we call it the "Init" container) that is responsible for things like publishing, indexing, etc. One of the tasks is to auto-rebuild **Sitecore marketing definitions** which must be done in order for Pattern Cards and Profiles to work.

This error will result if Marketing Definitions are not rebuilt properly. You will be able to see in the logs for the Init container if there were any issues or if Marketing Definitions were rebuilt as expected. Note that it can sometimes take a few extra minutes for the Init container to complete.

If for any reason, the Init container does not auto-rebuild the Marketing Definitions then go ahead and manually rebuild them from the Sitecore Control Panel. Please let us know if any issues after Marketing Definitions are rebuilt.

**Comment by dmead35** [comment]
ok thanks for the explanation and workaround steps provided if it happens again
